/**
 * Subject display metadata and dataset filename.
 * Each subject has: id, name, shortName, color, icon, file, semesterId, prerequisiteId?
 *
 * semesterId values: 'sem1' | 'sem2' | 'sem3' | 'sem4' | null (for prereq/foundation subjects)
 */
const SUBJECT_DEFINITIONS = [

  // ─── Foundation / Prerequisite Subjects (no semester) ─────────────────────
  {
    id: '12th_math',
    name: '12th Mathematics (Complex Numbers & Matrices)',
    shortName: '12th Math',
    color: '#a78bfa',
    icon: '📐',
    file: '12th-math.json',
    semesterId: null,
    prerequisiteId: undefined,
  },
  {
    id: '12th_phy',
    name: '12th Physics (Dual Nature & Optics)',
    shortName: '12th Physics',
    color: '#fbbf24',
    icon: '🔬',
    file: '12th-phy.json',
    semesterId: null,
    prerequisiteId: undefined,
  },
  {
    id: 'pre_bee',
    name: 'BEE Prerequisites (Current Electricity Basics)',
    shortName: 'Pre-BEE',
    color: '#f87171',
    icon: '🔌',
    file: 'pre-bee.json',
    semesterId: null,
    prerequisiteId: undefined,
  },
  {
    id: 'pre_mech',
    name: 'Mechanics Prerequisites (Laws of Motion & Vectors)',
    shortName: 'Pre-Mech',
    color: '#22d3ee',
    icon: '📏',
    file: 'pre-eng-mech.json',
    semesterId: null,
    prerequisiteId: undefined,
  },

  // ─── Semester 1 ────────────────────────────────────────────────────────────
  {
    id: 'math1',
    name: 'Engineering Mathematics 1',
    shortName: 'Math I',
    color: '#8b5cf6',
    icon: '∑',
    file: 'm1.json',
    semesterId: 'sem1',
    prerequisiteId: '12th_math',
  },
  {
    id: 'phy1',
    name: 'Engineering Physics 1',
    shortName: 'Physics I',
    color: '#f59e0b',
    icon: '⚛',
    file: 'phy1.json',
    semesterId: 'sem1',
    prerequisiteId: '12th_phy',
  },
  {
    id: 'chem1',
    name: 'Engineering Chemistry 1',
    shortName: 'Chemistry I',
    color: '#10b981',
    icon: '⚗',
    file: 'chem1.json',
    semesterId: 'sem1',
    prerequisiteId: undefined,
  },
  {
    id: 'bee',
    name: 'Basic Electrical Engineering',
    shortName: 'BEE',
    color: '#ef4444',
    icon: '⚡',
    file: 'eng-bee.json',
    semesterId: 'sem1',
    prerequisiteId: 'pre_bee',
  },
  {
    id: 'eg',
    name: 'Engineering Graphics',
    shortName: 'Eng. Graphics',
    color: '#3b82f6',
    icon: '📐',
    file: 'eng-graphics.json',
    semesterId: 'sem1',
    prerequisiteId: undefined,
  },
  {
    id: 'pce1',
    name: 'Professional Communication English 1',
    shortName: 'PCE-1',
    color: '#ec4899',
    icon: '💬',
    file: 'pce1.json',
    semesterId: 'sem1',
    prerequisiteId: undefined,
  },

  // ─── Semester 2 ────────────────────────────────────────────────────────────
  {
    id: 'm2',
    name: 'Engineering Mathematics 2',
    shortName: 'Math II',
    color: '#7c3aed',
    icon: '∫',
    file: 'm2.json',
    semesterId: 'sem2',
    prerequisiteId: 'math1',
  },
  {
    id: 'phy2',
    name: 'Engineering Physics 2',
    shortName: 'Physics II',
    color: '#f97316',
    icon: '🧲',
    file: 'phy2.json',
    semesterId: 'sem2',
    prerequisiteId: 'phy1',
  },
  {
    id: 'chem2',
    name: 'Engineering Chemistry 2',
    shortName: 'Chemistry II',
    color: '#14b8a6',
    icon: '🧪',
    file: 'chem2.json',
    semesterId: 'sem2',
    prerequisiteId: 'chem1',
  },
  {
    id: 'mech',
    name: 'Engineering Mechanics',
    shortName: 'Eng. Mech',
    color: '#06b6d4',
    icon: '⚙',
    file: 'eng-mech.json',
    semesterId: 'sem2',
    prerequisiteId: 'pre_mech',
  },
  {
    id: 'cp',
    name: 'Computer Programming (C)',
    shortName: 'C Programming',
    color: '#eab308',
    icon: '💻',
    file: 'cp.json',
    semesterId: 'sem2',
    prerequisiteId: undefined,
  },

  // ─── Semester 3 ────────────────────────────────────────────────────────────
  {
    id: 'm3',
    name: 'Engineering Mathematics 3',
    shortName: 'Math III',
    color: '#a855f7',
    icon: '∂',
    file: 'm3.json',
    semesterId: 'sem3',
    prerequisiteId: 'm2',
  },
  {
    id: 'ds',
    name: 'Data Structures',
    shortName: 'DS',
    color: '#22c55e',
    icon: '🌲',
    file: 'ds.json',
    semesterId: 'sem3',
    prerequisiteId: 'cp',
  },
  {
    id: 'dlcoa',
    name: 'Digital Logic & Computer Organization',
    shortName: 'DLCOA',
    color: '#f43f5e',
    icon: '🔢',
    file: 'dlcoa.json',
    semesterId: 'sem3',
    prerequisiteId: undefined,
  },
  {
    id: 'dsgt',
    name: 'Discrete Structures & Graph Theory',
    shortName: 'DSGT',
    color: '#818cf8',
    icon: '🔷',
    file: 'dsgt.json',
    semesterId: 'sem3',
    prerequisiteId: undefined,
  },
  {
    id: 'mp',
    name: 'Microprocessors',
    shortName: 'Microprocessors',
    color: '#10b981',
    icon: '🖥',
    file: 'mp.json',
    semesterId: 'sem3',
    prerequisiteId: 'dlcoa',
  },

  // ─── Semester 4 ────────────────────────────────────────────────────────────
  {
    id: 'm4',
    name: 'Engineering Mathematics 4',
    shortName: 'Math IV',
    color: '#6366f1',
    icon: 'λ',
    file: 'm4.json',
    semesterId: 'sem4',
    prerequisiteId: 'm3',
  },
  {
    id: 'dbms',
    name: 'Database Management Systems',
    shortName: 'DBMS',
    color: '#f43f5e',
    icon: '🗄️',
    file: 'dbms.json',
    semesterId: 'sem4',
    prerequisiteId: 'ds',
  },
  {
    id: 'os',
    name: 'Operating Systems',
    shortName: 'OS',
    color: '#0ea5e9',
    icon: '🖥️',
    file: 'os.json',
    semesterId: 'sem4',
    prerequisiteId: 'cp',
  },
  {
    id: 'aoa',
    name: 'Analysis of Algorithms',
    shortName: 'AOA',
    color: '#f59e0b',
    icon: '⚗️',
    file: 'aoa.json',
    semesterId: 'sem4',
    prerequisiteId: 'ds',
  },
  {
    id: 'cg',
    name: 'Computer Graphics',
    shortName: 'CG',
    color: '#06b6d4',
    icon: '🎨',
    file: 'cg.json',
    semesterId: 'sem4',
    prerequisiteId: undefined,
  },
];

module.exports = { SUBJECT_DEFINITIONS };
